system_define_ledgers = {
    'assets' : [
        ['Current Assets', 'def-11', 0],
        ['Loans', 'def-111', 'def-11'],
        ['Provision For Loan Loss', 'def-1111', 'def-111'],
        ['Loan Loss Provision', 'def-112', 'def-11'],
        ['Receivables', 'def-113', 'def-11'],
        ['Sms Payment Receivable', 'def-1131', 'def-113'],
        ['Booked Savings Receivable', 'def-1132', 'def-113'],
        ['Inventory/Stock Receivable', 'def-1133', 'def-113'],
        ['Liquid Assets', 'def-114', 'def-11'],
        ['Bank Accounts, Cash, & Mobile Money', 'def-1141', 'def-114'],
        ['Bank Accounts', 'def-11411', 'def-1141'],
        ['Cash Accounts', 'def-11412', 'def-1141'],
        ['Teller Accounts', 'def-11413', 'def-1141'],
        ['Mobile Money Accounts', 'def-11414', 'def-1141'],
        ['Inter-Branch Cash Accounts', 'def-11416', 'def-1141'],
        ['Inventory', 'def-115', 'def-11'],
        ['Savings Over Drafts', 'def-116', 'def-11'],
        ['Cash Suspense', 'def-117', 'def-11'],
        ['Non Current Assets', 'def-12', 0],
        ['Fixed Assets', 'def-121', 'def-12'],
        ['Land', 'def-1211', 'def-121'],
        ['Other Assets', 'def-122', 'def-12'],
        ['Investments', 'def-123', 'def-12'],
        ['Liquid Investments', 'def-1231', 'def-123'],
        ['Financial Investments', 'def-1232', 'def-123']
    ],
    'liabilities': [
        ['Current Liabilities', 'def-21', 0],
        ['Accounts  Payable', 'def-212', 'def-21'],
        ['Payable Sms', 'def-2121', 'def-212'],
        ['Fd Withholding Tax Payable', 'def-2122', 'def-212'],
        ['Savings & Deposits', 'def-211', 'def-21'],
        ['Fixed Deposits', 'def-2111', 'def-211'],
        ['Loans Payable', 'def-213', 'def-21'],
        ['Short-Term Loans Payable ( <=1 Year)', 'def-2131', 'def-213'],
        ['Long-Term Loans Payable ( > 1 Year)', 'def-2132', 'def-213'],
        ['Savings Dividends Payable', 'def-214', 'def-21'],
        ['Savings Accounts Reconciliation Suspense', 'def-215', 'def-21'],
        ['Non-Cash Collections From Members-Payable', 'def-216', 'def-21'],
        ['Withholding Tax Payable', 'def-217', 'def-21'],
        ['Witholding Tax Payable 6%', 'def-2171', 'def-217'],
        ['Witholding Tax Payable 15%', 'def-2172', 'def-217'],
        ['Non Current Liabilities', 'def-22', 0],
        ['Long-Term Loans Payable (> 1 Year)', 'def-221', 'def-22']
    ],
    'capital': [
        ['Member Share Capital', 'def-31', 0],
        ['Member Shares', 'def-311', 'def-31'],
        ['Inter Branch Share Transfer', 'def-312', 'def-31'],
        ['Institutional Capital', 'def-32', 0],
        ['Reserves', 'def-321', 'def-32'],
        ['Statutory Legal Reserves', 'def-3211', 'def-321'],
        ['Share Transfer Fund', 'def-3212', 'def-321'],
        ['Donations And Grant', 'def-322', 'def-32'],
        ['Retained Earnings/Capital Reserves', 'def-323', 'def-32'],
        ['Current Period Earnings', 'def-33', 0]
    ],
    'income': [
        ['Interest Income', 'def-41', 0],
        ['Income From Loans', 'def-411', 'def-41'],
        ['Loan Penalty Income', 'def-4116', 'def-411'],
        ['Loan Interest Income', 'def-4115', 'def-411'],
        ['Loan Application Fee', 'def-4111', 'def-411'],
        ['Loan Insurance Fees', 'def-4112', 'def-411'],
        ['Loan Monitoring Fees', 'def-4113', 'def-411'],
        ['Loan Appraisal/Assessment Fees', 'def-4114', 'def-411'],
        ['Income On Liquid Investments', 'def-412', 'def-41'],
        ['Income On Financial Investments', 'def-413', 'def-41'],
        ['Other Interest Income', 'def-414', 'def-41'],
        ['Non Interest Income', 'def-42', 0],
        ['Income From Member Savings & Deposits', 'def-421', 'def-42'],
        ['Income From Savings Transfer Charges', 'def-4211', 'def-421'],
        ['Income From Savings Withdrawal Charges', 'def-4212', 'def-421'],
        ['Income From Savings Deposit Charges', 'def-4213', 'def-421'],
        ['Income From Savings Monthly Charges', 'def-4214', 'def-421'],
        ['Income From Fixed Deposit Penalty', 'def-4215', 'def-421'],
        ['Income From Sms Charges', 'def-422', 'def-42'],
        ['Incomes From Sms', 'def-4221', 'def-422'],
        ['Income From Mobile Money Transactions', 'def-423', 'def-42'],
        ['Incomes From Mobile Money Deposits', 'def-4231', 'def-423'],
        ['Incomes From Mobile Money Withdrawals', 'def-4232', 'def-423'],
        ['Income On Mobile Banking Transactions', 'def-4233', 'def-423'],
        ['Income From Sale On Fixed Assets', 'def-424', 'def-42'],
        ['Other Non-Interest Income', 'def-425', 'def-42'],
        ['Gain On Asset Disposal', 'def-4251', 'def-425'],
        ['Income From Sale Of Inventory', 'def-4252', 'def-425'],
        ['Income From Bad Debts Recovered', 'def-426', 'def-42'],
        ['Income From Account Management', 'def-427', 'def-42'],
        ['Non-Financial Investment Income', 'def-428', 'def-42'],
        ['Income Receivables', 'def-429', 'def-42'],
        ['Registered Receivables', 'def-4291', 'def-429'],
        ['Income From Sale Of Member Collections', 'def-4201', 'def-42'],
        ['Income From Savings Account Management', 'def-4202', 'def-42'], 
        ['Income From Account Closure', 'def-42021', 'def-4202'], 
        ['Income From Uploads Of Savings Remittances', 'def-42022', 'def-4202']
    ],
    'expenses': [
        ['Financial Costs', 'def-51', 0],
        ['Finance Costs On Savings And Deposits', 'def-511', 'def-51'],
        ['Savings Accounts Interest', 'def-5111', 'def-511'],
        ['Fixed Deposit Interest Bonus', 'def-5112', 'def-511'],
        ['Fixed Deposit Interest', 'def-5113', 'def-511'],
        ['Finance Costs On Loan Payable', 'def-512', 'def-51'],
        ['Loans Payable Interest Expense Account', 'def-5121', 'def-512'],
        ['Finance Costs On Accounts Payable', 'def-513', 'def-51'],
        ['Finance Costs On Shares', 'def-514', 'def-51'],
        ['Finance Costs Bank Charges', 'def-515', 'def-51'],
        ['Bank Transfer Charges', 'def-5151', 'def-515'],
        ['Written Off Loans', 'def-516', 'def-51'],
        ['Finance Costs On Mobile Banking', 'def-517', 'def-51'],
        ['Charges On Mobile Banking Transactions', 'def-5171', 'def-517'],
        ['Loss From Sale Of Inventory', 'def-518', 'def-51'],
        ['Non-Financial Costs', 'def-52', 0],
        ['Costs Of Non-Financial Investments', 'def-521', 'def-52'],
        ['Operating Expenses', 'def-53', 0],
        ['Personnal Expenses', 'def-531', 'def-53'],
        ['Governance Expenses', 'def-532', 'def-53'],
        ['Marketing & Sales Expenses', 'def-533', 'def-53'],
        ['Depreciation And Amortization', 'def-534', 'def-53'],
        ['Asset Depreciation', 'def-5341', 'def-534'],
        ['Amortization', 'def-5342', 'def-534'],
        ['Administrative Expenses', 'def-535', 'def-53'],
        ['Sms Purchase Costs', 'def-536', 'def-53'],
        ['Loss On Asset Disposal', 'def-537', 'def-53'],
        ['Cost Of Sale-Member Collections', 'def-538', 'def-53'],
        ['Provision Expenses For Risk Assets', 'def-54', 0]
    ]
}